version: "3"
services:
    node:
        build: ./frontend
        ports: 
            - "8080:8080"
        restart: always
        volumes:
            - .:/home/node/app    
            - /home/node/app/node_modules