# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest-browsers
        environment:
          NODE_ENV: development

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run:
          name: "Add missing library to run puppeteer"
          command: sudo apt-get install -yq libxtst6

      - run: 
          name: "Install wait-on package globally"
          command: sudo npm install -g wait-on

      - run: npm install

      - run:
          name: "Rebuild node-sass if needed"
          command: npm run prebuild

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Indicate that tests are running on CircleCI"
          command: echo "export TEST_ENV=circle_ci" >> $BASH_ENV

      - run: 
          npm run build

      - run:
          name: "Running client server"
          command: npm run start
          background: true

      - run: 
          wait-on http://127.0.0.1:8080 && npm run test-not-watch
